import{a as S,S as q,i as c}from"./assets/vendor-LK6CqzKq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&o(h)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const P="https://pixabay.com/api/",x="51408648-c1ffe0deedea697cddb1d0199";async function m(r,t=1,a=15){const o={key:x,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a};return(await S.get(P,{params:o})).data}const R=document.querySelector(".gallery"),y=document.querySelector(".load-more"),g=document.querySelector(".loader-wrapper"),M=new q(".gallery a",{});function L(r){const t=document.querySelector(".gallery"),a=r.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
        </a>
       <div class="info">
      <p>Likes: ${o.likes}</p>
      <p>Views: ${o.views}</p>
      <p>Comments: ${o.comments}</p>
      <p>Downloads: ${o.downloads}</p>
    </div>

      </li>
    `).join("");t.insertAdjacentHTML("beforeend",a),M.refresh()}function T(){R.innerHTML=""}function w(){g.classList.remove("is-hidden")}function i(){g.classList.add("is-hidden")}function v(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}const f=document.querySelector(".form");document.querySelector('input[name="search-text"]');let l="",n=1;const b=15;let p=0;f.addEventListener("submit",async r=>{if(r.preventDefault(),l=f.elements["search-text"].value.trim(),!l){i();return}n=1,w(),T(),d();try{const{hits:t,totalHits:a}=await m(l,n);if(await u(800),t.length===0){c.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i();return}p=a,L(t),i(),v();const o=Math.ceil(p/b);n>=o&&(d(),c.info({message:"The end of search results.",position:"topRight"}))}catch{await u(800),i(),c.error({message:"We are sorry, but you have reached the end of search results.",position:"topRight"})}});document.querySelector(".load-more").addEventListener("click",async()=>{n+=1,d(),w(),showLoaderText();try{const{hits:r}=await m(l,n);await u(800),L(r);const t=Math.ceil(p/b);n>=t?(d(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v(),i(),hideLoaderText();const{height:a}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch{await u(800),i(),hideLoaderText(),c.error({message:"Error loading more images.",position:"topRight"})}});function u(r){return new Promise(t=>setTimeout(t,r))}
//# sourceMappingURL=index.js.map
