import{a as v,S,i}from"./assets/vendor-LK6CqzKq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&t(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b="https://pixabay.com/api/",q="51408648-c1ffe0deedea697cddb1d0199";async function f(s,r=1,a=15){const t={key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await v.get(b,{params:t})).data}const P=document.querySelector(".gallery");document.querySelector(".loader");const M=new S(".gallery a",{});function m(s){const r=document.querySelector(".gallery"),a=s.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
       <div class="info">
      <p>Likes: ${t.likes}</p>
      <p>Views: ${t.views}</p>
      <p>Comments: ${t.comments}</p>
      <p>Downloads: ${t.downloads}</p>
    </div>

      </li>
    `).join("");r.insertAdjacentHTML("beforeend",a),M.refresh()}function R(){P.innerHTML=""}const y=document.querySelector(".load-more"),g=document.querySelector(".loader-wrapper");function L(){g.classList.remove("is-hidden")}function l(){g.classList.add("is-hidden")}function B(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}const h=document.querySelector(".form");document.querySelector('input[name="search-text"]');const $=document.querySelector(".load-more");let c="",n=1;const w=15;let p=0;h.addEventListener("submit",async s=>{if(s.preventDefault(),c=h.elements["search-text"].value.trim(),!!c){n=1,R(),u(),L();try{const{hits:r,totalHits:a}=await f(c,n);if(l(),r.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=a,m(r),B();const t=Math.ceil(p/w);n>=t&&(u(),i.info({message:"The end of search results.",position:"topRight"}))}catch{l(),i.error({message:"We are sorry, but you have reached the end of search results.",position:"topRight"})}}});$.addEventListener("click",async()=>{n+=1,L();try{const{hits:s}=await f(c,n);m(s);const r=Math.ceil(p/w);n>=r&&(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),l();const{height:a}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch{l(),i.error({message:"Error",position:"topRight"})}});
//# sourceMappingURL=index.js.map
