import{a as b,S,i as c}from"./assets/vendor-LK6CqzKq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&t(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",P="51408648-c1ffe0deedea697cddb1d0199";async function f(s,r=1,a=15){const t={key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a};return(await b.get(q,{params:t})).data}const R=document.querySelector(".gallery"),m=document.querySelector(".load-more"),y=document.querySelector(".loader-wrapper"),M=new S(".gallery a",{});function g(s){const r=document.querySelector(".gallery"),a=s.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
       <div class="info">
      <p>Likes: ${t.likes}</p>
      <p>Views: ${t.views}</p>
      <p>Comments: ${t.comments}</p>
      <p>Downloads: ${t.downloads}</p>
    </div>

      </li>
    `).join("");r.insertAdjacentHTML("beforeend",a),M.refresh()}function B(){R.innerHTML=""}function L(){y.classList.remove("is-hidden")}function n(){y.classList.add("is-hidden")}function w(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}const h=document.querySelector(".form");document.querySelector('input[name="search-text"]');let l="",i=1;const v=15;let p=0;h.addEventListener("submit",async s=>{if(s.preventDefault(),l=h.elements["search-text"].value.trim(),!l){n();return}i=1,L(),B(),d();try{const{hits:r,totalHits:a}=await f(l,i);if(r.length===0){c.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n();return}p=a,g(r),n(),w();const t=Math.ceil(p/v);i>=t&&(d(),c.info({message:"The end of search results.",position:"topRight"}))}catch{n(),c.error({message:"We are sorry, but you have reached the end of search results.",position:"topRight"})}});document.querySelector(".load-more").addEventListener("click",async()=>{i+=1,d(),L();try{const{hits:s}=await f(l,i);g(s);const r=Math.ceil(p/v);i>=r?(d(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(),n();const{height:a}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch{n(),c.error({message:"Error loading more images.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
